### ISSUE TITLE
Passwords with % causes error

### ISSUE THREAD

**Issue by inamine** [nodemailer/nodemailer-shared#1]
Hi there,

I tried to create a SMTP transporter using gmail account, but looks like that using escaped password with special characters (such as '%') causes an error: Malformed URI.
My code:
`transporter = nodemailer.createTransport("smtps://user%40gmail.com:passwith%25Char@smtp.gmail.com");`

Investigated, I found the follow issue: The project nodemailer-shared use url.parse and get user and password that are not encoded to decoded again(line 48/49).

This is throwing the error.

**Comment by andris9** [comment]
Fixed. Upgrade nodemailer to v2.4.0 to use this fix
